// Fastify JSON Schema for Character input validation
export const characterSchema = {
    type: 'object',
    required: [
        'id',
        'name',
        'health',
        'mana',
        'strength',
        'dexterity',
        'constitution',
        'intelligence',
        'wisdom',
        'charisma',
        'race',
        'archetype',
        'author',
        'isPublic',
        'createdAt',
        'updatedAt',
    ],
    properties: {
        id: { type: 'integer' },
        name: { type: 'string', minLength: 1 },
        surname: { type: 'string' },
        nickname: { type: 'string' },
        description: { type: 'string' },
        avatar: { type: 'string' },
        health: { type: 'integer' },
        mana: { type: 'integer' },
        strength: { type: 'integer' },
        dexterity: { type: 'integer' },
        constitution: { type: 'integer' },
        intelligence: { type: 'integer' },
        wisdom: { type: 'integer' },
        charisma: { type: 'integer' },
        race: { $ref: 'raceSchema#' },
        archetype: { $ref: 'archetypeSchema#' },
        items: { type: 'array', items: { $ref: 'itemSchema#' } },
        primaryWeapon: { $ref: 'itemSchema#' },
        secondaryWeapon: { $ref: 'itemSchema#' },
        shield: { $ref: 'itemSchema#' },
        armor: { $ref: 'itemSchema#' },
        firstRing: { $ref: 'itemSchema#' },
        secondRing: { $ref: 'itemSchema#' },
        amulet: { $ref: 'itemSchema#' },
        author: { $ref: 'authorSchema#' },
        isPublic: { type: 'boolean' },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
    },
    additionalProperties: false,
}

// Example: import and use in route
// import { characterSchema } from '../schemas/character.schema';
// fastify.post('/characters', { schema: { body: characterSchema }, handler: ... })
